 const data =  {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            image: './images/p1.jpeg',
            price: 120,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
            countInStock: 5,
        },
        {
            _id: '2',
            name: 'Adidads Fit Shirt',
            image: './images/p2.jpeg',
            price: 100,
            brand:'Nike',
            rating: 4,
            numReviews: 10,
            description: 'high quality product',
            countInStock: 0,
        },
        {
            _id: '3',
            name: 'Lee suit Shirt',
            image: './images/p3.jpeg',
            price: 198,
            brand:'Nike',
            rating: 4,
            numReviews: 120,
            description: 'high quality product',
            countInStock: 5,
        },
        {
            _id: '4',
            name: 'Nike Slim Pants',
            image: './images/p4.jpeg',
            price: 110,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
            countInStock: 5,
        },
        {
            _id: '5',
            name: 'Jean top Shirt',
            image: './images/p5.jpeg',
            price: 150,
            brand:'Nike',
            rating: 5,
            numReviews: 40,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Puma Fit Pants',
            image: './images/p6.jpeg',
            price: 167,
            brand:'Nike',
            rating: 4.5,
            numReviews: 102,
            description: 'high quality product',
            countInStock: 5,
        },
  
    ]
}

export default data